routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//});

Route::get('/',[\App\Http\Controllers\Main\maincontroller::class,'index'])->name('main.index');
Route::get('/search',[\App\Http\Controllers\Main\maincontroller::class,'search'])->name('search');
Route::get('/detail/{book}/',[\App\Http\Controllers\Main\maincontroller::class,'book_detail'])->name('book.detail');
Route::get('/category/{id}',[\App\Http\Controllers\Main\maincontroller::class,'category_filter'])->name('category.filter');
Route::get('/author/{id}',[\App\Http\Controllers\Main\maincontroller::class,'author_filter'])->name('author.filter');
Route::get('/card/{id}',[\App\Http\Controllers\Main\maincontroller::class,'added_cards'])->name('added.cards');
Route::get('/view_card',[\App\Http\Controllers\Main\maincontroller::class,'view_card'])->name('view.card');
Route::get('/cancel/{id}',[\App\Http\Controllers\Main\maincontroller::class,'cancel_book'])->name('cansel.book');
Route::get('/contact',[\App\Http\Controllers\Main\maincontroller::class,'contact'])->name('contact');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('admin_panel');

    Route::resource('/category', \App\Http\Controllers\Admin\categoryController::class);

    Route::resource('/books', App\Http\Controllers\Admin\BookController::class);
});
//Route::group(['prefix' => 'User', 'middleware' => ['auth', 'user']], function () {
//    Route::get('/', [\App\Http\Controllers\HomeController::class, 'user'])->name('userpanel');
//
//
//
//});

Route::post('/comment',[\App\Http\Controllers\CommentComtroller::class,'store'])->name('comment')->middleware('auth');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::post('/payment',[\App\Http\Controllers\ChecoutController::class,'session'])->name('data');
Route::get('/success',[\App\Http\Controllers\ChecoutController::class,'success'])->name('success');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable=[
      'category_name'
    ];
}

app/Http/Controllers/Admin/categoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Books;
use App\Models\Category;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class categoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id','desc')->get();

        $title = 'Delete category!';
        $text = "Are you sure you want to delete?";
        confirmDelete($title, $text);
        return  view('admin.category.view', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('admin.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request ->validate([
            'category_name'=>'required'
            ]);
        $category = new Category();
        $category->category_name =$request->category_name;
        $category->save();
        Alert::success('Success Title', 'Category created successfully');

//        return redirect()->route('category.index');
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return  view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request ->validate([
            'category_name'=>'required'
        ]);
        $category = Category::find($id);
        $category->category_name =$request->category_name;
        $category->update();
        Alert::success('Success Title', 'Category changed successfully');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category  $category, Books $books)
    {
        $books = Books::where('category_id','=',$category->id)->delete();
        $category->delete();
        Alert::success('Success Title', 'Category deleted successfully');

        $title = 'Delete User!';
        $text = "Are you sure you want to delete?";
        confirmDelete($title, $text);



        return redirect()->back();
    }
}

resources/views/admin/category/add.blade.php
@extends('admin.layouts.master');
@section('title','Add category')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Add
                                    category</font></font></span></h5>
                    </div>

                    <div class="card-body">
                        <form class="form-wizard" id="regForm" action="{{route('category.store')}}" method="POST">
                            @csrf
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Category name</font></font></label>
                                    <input name="category_name"
                                           class="form-control  @error('category_name') is-invalid @enderror" id="name"
                                           type="text" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>
                                @error('category_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <br>
                            <div>
                                <div class="text-end btn-mb">
                                    <button type="submit" class="btn btn-success"> Add category</button>
                                </div>
                            </div>
                            <!-- Circles which indicates the steps of the form:-->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.master');
@section('title','Edit categoru')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Add category</font></font></span></h5>
                    </div>
                    <div class="card-body">
                        <form class="form-wizard" id="regForm" action="{{route('category.update',$category->id)}}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Category name</font></font></label>
                                    <input value="{{$category->category_name}}" name="category_name" class="form-control  @error('email') is-invalid @enderror" id="name" type="text" placeholder="" required="required" data-bs-original-title="" title="">
                                </div>
                                @error('category_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>


                            <br>
                            <div>
                                <div class="text-end btn-mb">
                                    <button type="submit" class="btn btn-success"> Update category</button>
                                </div>
                            </div>
                            <!-- Circles which indicates the steps of the form:-->

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/category/view.blade.php
@extends('admin.layouts.master')
@section('title','View category')
@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>All categories</h5>
                <a href="{{route('category.create')}}" class="btn btn-primary">create category</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display" id="basic-1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Category title</th>
                            <th>Added date</th>

                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $key=>$category)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$category->category_name}}</td>
                                <td>{{$category->created_at}}</td>


                                <td class="d-flex">
                                    <a href="{{route('category.edit',$category)}}" class="btn btn-success">Edit</a>

{{--                                    <form action="{{route('category.destroy',$category->id)}}" method="POST"--}}
{{--                                          onsubmit="return confirm('Rostdan ham {{$category->category_name}} o\'chirishni xoxlaysizmi  ? ')">--}}
{{--                                        @method('Delete')--}}
{{--                                        @csrf--}}
{{--                                        <button class=" btn btn-sm btn-danger show_confirm" type="submit "><i--}}
{{--                                                class="fa fa-trash-o"></i>--}}
{{--                                        </button>--}}
{{--                                    </form>--}}

                                    <a href=" {{route('category.destroy',$category->id)}}" class="btn btn-danger" data-confirm-delete="true">Delete</a>


                                    {{--                                    &nbsp;<form action="{{route('category.destroy',$category->id)}}" method="post">--}}
{{--                                        @csrf--}}
{{--                                        @method('DELETE')--}}
{{--                                        <button type="submit" class="btn btn-danger show_confirm">Delete</button>--}}
{{--                                    </form>--}}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection