routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//});

Route::get('/',[\App\Http\Controllers\Main\maincontroller::class,'index'])->name('main.index');
Route::get('/search',[\App\Http\Controllers\Main\maincontroller::class,'search'])->name('search');
Route::get('/detail/{book}/',[\App\Http\Controllers\Main\maincontroller::class,'book_detail'])->name('book.detail');
Route::get('/category/{id}',[\App\Http\Controllers\Main\maincontroller::class,'category_filter'])->name('category.filter');
Route::get('/author/{id}',[\App\Http\Controllers\Main\maincontroller::class,'author_filter'])->name('author.filter');
Route::get('/card/{id}',[\App\Http\Controllers\Main\maincontroller::class,'added_cards'])->name('added.cards');
Route::get('/view_card',[\App\Http\Controllers\Main\maincontroller::class,'view_card'])->name('view.card');
Route::get('/cancel/{id}',[\App\Http\Controllers\Main\maincontroller::class,'cancel_book'])->name('cansel.book');
Route::get('/contact',[\App\Http\Controllers\Main\maincontroller::class,'contact'])->name('contact');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('admin_panel');

    Route::resource('/category', \App\Http\Controllers\Admin\categoryController::class);

    Route::resource('/books', App\Http\Controllers\Admin\BookController::class);
});
//Route::group(['prefix' => 'User', 'middleware' => ['auth', 'user']], function () {
//    Route::get('/', [\App\Http\Controllers\HomeController::class, 'user'])->name('userpanel');
//
//
//
//});

Route::post('/comment',[\App\Http\Controllers\CommentComtroller::class,'store'])->name('comment')->middleware('auth');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::post('/payment',[\App\Http\Controllers\ChecoutController::class,'session'])->name('data');
Route::get('/success',[\App\Http\Controllers\ChecoutController::class,'success'])->name('success');

app/Models/Books.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Books extends Model
{
    use HasFactory;

    protected $fillable = [
        'book_name',
        'book_author',
        'category_id',
        'book_prise',
        'book_images',
        'book_description',
    ];


    public function category_name()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function comments()
    {
        return $this->hasMany(Commente::class);
    }

    public  function user()
    {
        return $this->belongsTo(User::class);
    }


}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\BookEvent;
use App\Http\Controllers\Controller;
use App\Models\Books;
use App\Models\Category;
use App\Models\Commente;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use RealRashid\SweetAlert\Facades\Alert;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $books = Books::orderBy('id', 'desc')->get();
//        $book_img = explode('<!',$books->book_images);
        $title = 'Delete book!';
        $text = "Are you sure you want to delete?";
        confirmDelete($title, $text);

        return view('admin.book.view', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.book.add', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'book_name' => 'required',
            'book_author' => 'required',
            'category_id' => 'required',
            'book_prise' => 'required',
            'book_img' => 'required|array',
            'book_description' => 'required',

        ]);

        $book_name = $request->book_name;
        $book_author = $request->input('book_author');
        $category_id = $request->input('category_id');
        $book_prise = $request->input('book_prise');
        $book_description = $request->input('book_description');

        $images = '';

        for ($i = 0; $i < count($request->file('book_img')); $i++) {
            $all_img = $request->file('book_img')[$i];
            $extension = $all_img->getClientOriginalExtension();
            $fileNameToStore = time();
            $images .= $fileNameToStore . $i . '.' . $extension . '<!';
            $all_img->move(public_path('admin/book_images/'), $fileNameToStore . $i . '.' . $extension);
        }
        $books = new Books();
        $books->book_name = $book_name;
        $books->book_author = $book_author;
        $books->category_id = $category_id;
        $books->book_prise = $book_prise;
        $books->book_images = $images;
        $books->book_description = $book_description;
        $books->save();
        event(new BookEvent('hello world'));
//        event(new BookEvent("You created successfully"));
        Alert::success('Success Title', 'Book created successfully');
//        event(new BookEvent($books) );
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Books $book)
    {

        $book_img = explode('<!', $book->book_images);
        return view('admin.book.show', compact('book', 'book_img'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Books $book)
    {
        $categories = Category::all();
        $book_img = explode('<!', $book->book_images);
        return view('admin.book.edit', compact('book', 'categories', 'book_img'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Books $book)
    {


        $request->validate([
            'book_name' => 'required',
            'book_author' => 'required',
            'category_id' => 'required',
            'book_prise' => 'required',
//                'book_img' => 'required|array',
            'book_description' => 'required',

        ]);

        $book_name = $request->book_name;
        $book_author = $request->input('book_author');
        $category_id = $request->input('category_id');
        $book_prise = $request->input('book_prise');
        $book_description = $request->input('book_description');

        if ($request->hasFile('book_img')) {
            $old_img = explode('<!', $book->book_images);
            for ($i = 0; $i < count($old_img) - 1; $i++) {
                File::delete(public_path('admin/book_images/' . $old_img[$i]));
            }


            $images = '';

            for ($i = 0; $i < count($request->file('book_img')); $i++) {
                $all_img = $request->file('book_img')[$i];
                $extension = $all_img->getClientOriginalExtension();
                $fileNameToStore = time();
                $images .= $fileNameToStore . $i . '.' . $extension . '<!';
//                    $org_img = $fileNameToStore . $i . '.' . $extension.'<!';
//                    array_push($images, $org_img);
                $all_img->move(public_path('admin/book_images/'), $fileNameToStore . $i . '.' . $extension);
            }

        } else {
            $images = $book->book_images;
        }

//            $images = implode($images,'<!');
//            $books = new Books();
        $book->book_name = $book_name;
        $book->book_author = $book_author;
        $book->category_id = $category_id;
        $book->book_prise = $book_prise;
        $book->book_images = $images;
        $book->book_description = $book_description;
        $book->update();
        Alert::success('Success Title', 'Book changed successfully');
        return redirect()->route('books.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Books $book)
    {
        $old_img = explode('<!', $book->book_images);
        for ($i = 0; $i < count($old_img) - 1; $i++) {
            File::delete(public_path('admin/book_images/' . $old_img[$i]));
        }
        $book->delete();

//
        Alert::success('Success Title', 'Book deleted successfully');
        return redirect()->back();

    }
}

resources/views/admin/book/add.blade.php
@extends('admin.layouts.master');
@section('title','Add book')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Add
                                    Book</font></font></h5>
                    </div>
                    <div class="card-body">
                        <form class="form-wizard" id="regForm" action="{{route('books.index')}}" method="POST"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book name</font></font></label>
                                    <input name="book_name"
                                           class="form-control  @error('book_name') is-invalid @enderror" id="name"
                                           type="text" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>
                                @error('book_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book author</font></font></label>
                                    <input name="book_author"
                                           class="form-control  @error('book_author') is-invalid @enderror" id="name"
                                           type="text" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>
                                @error('book_author')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="" style="display: block;">
                                <div class="mb-3">
                                    <div class="mb-3">
                                        <label class="form-label" for="exampleFormControlSelect9"> Select
                                            category</label>
                                        <select name="category_id" class="form-select digits" id="exampleFormControlSelect9">

                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}">{{$category->category_name}}</option>
                                            @endforeach
                                        </select>
                                    </div>


                                </div>
                            </div>
                            <br>
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book prise</font></font></label>
                                    <input name="book_prise"
                                           class="form-control  @error('book_prise') is-invalid @enderror" id="name"
                                           type="number" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>

                                <br>
                                @error('book_prise')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book image</font></font></label>
                                    <input multiple name="book_img[]"
                                           class="form-control   @error('book_img') is-invalid @enderror" id="name"
                                           type="file" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>

                                <br>
                                @error('book_img')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div>
                                <label for="exampleFormControlTextarea1" class="form-label">Model description</label>
                                <textarea class="@error('book_description') is-invalid @enderror" id="editor1"
                                          name="book_description" cols="30" rows="10"></textarea>
                                @error('book_description')
                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                @enderror

                            </div>

                            <br>
                            <div class="text-end btn-mb">
                                <button type="submit" class="btn btn-success"> Add book</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/book/edit.blade.php
@extends('admin.layouts.master')
@section('title','Edit book')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Add
                                    Book</font></font></h5>
                    </div>
                    <div class="card-body">
                        <form class="form-wizard" id="regForm" action="{{route('books.update',$book)}}" method="POST"
                              enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book name</font></font></label>
                                    <input name="book_name" value="{{$book->book_name}}"
                                           class="form-control  @error('book_name') is-invalid @enderror" id="name"
                                           type="text" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>
                                @error('book_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book author</font></font></label>
                                    <input name="book_author" value="{{$book->book_author}}"
                                           class="form-control  @error('book_author') is-invalid @enderror" id="name"
                                           type="text" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>
                                @error('book_author')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div class="" style="display: block;">
                                <div class="mb-3">
                                    <div class="mb-3">
                                        <label class="form-label" for="exampleFormControlSelect9"> Select
                                            category</label>

                                            <select   name="category_id" class="form-select digits" id="exampleFormControlSelect9">

                                                @foreach($categories as $category)
                                                    @if($book->category_id == $category->id)
                                                        <option selected value="{{$category->id}}">{{$category->category_name}}</option>
                                                    @else
                                                        <option  value="{{$category->id}}">{{$category->category_name}}</option>
                                                    @endif
                                                @endforeach
                                            </select>

                                    </div>


                                </div>
                            </div>
                            <br>
                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book prise</font></font></label>
                                    <input name="book_prise" value="{{$book->book_prise}}"
                                           class="form-control  @error('book_prise') is-invalid @enderror" id="name"
                                           type="number" placeholder="" required="required" data-bs-original-title=""
                                           title="">
                                </div>

                                <br>
                                @error('book_prise')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            @for($i=0; $i<count($book_img)-1; $i++)

                                <img style="width: 100px; height: 100px" src="{{ asset('admin/book_images/'.$book_img[$i])}}" alt="">
                            @endfor
{{--                            @foreach(explode('<!',$book->book_images) as $image)--}}
{{--                                <img style="width: 100px; height: 100px" src="{{ asset('admin/book_images/'.$image)}}" alt="">--}}
{{--                          &nbsp--}}
{{--                            @endforeach--}}

{{--                            @for($i=0; $i<count($book->book_images); $i++)--}}
{{--                                 <img src="{{asset('admin/book_images/'.explode('<!',$book->book_images)[$i])}}" style="width: 80px; height: 80px; background: red " alt="">--}}
{{--                            @endfor--}}

                            <div class="tab" style="display: block;">
                                <div class="mb-3">
                                    <label for="name"><font style="vertical-align: inherit;"><font
                                                style="vertical-align: inherit;">Book image</font></font></label>
                                    <input multiple name="book_img[]"
                                           class="form-control   @error('book_img') is-invalid @enderror" id="name"
                                           type="file" placeholder=""  data-bs-original-title=""
                                           title="">
                                </div>

                                <br>
                                @error('book_img')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                            <div>
                                <label for="exampleFormControlTextarea1" class="form-label">Model description</label>
                                <textarea class="@error('book_description') is-invalid @enderror" id="editor1"
                                          name="book_description" cols="30" rows="10">{!! $book->book_description !!}</textarea>
                                @error('book_description')
                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                @enderror

                            </div>

                            <br>
                            <div class="text-end btn-mb">
                                <button type="submit" class="btn btn-success"> Update book</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/book/view.blade.php
@extends('admin.layouts.master')
@section('title','Views all books')
@section('content')

    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>All categories</h5>
                <a href="{{route('books.create')}}" class="btn btn-primary">create book</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display" id="basic-1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Book name</th>
                            <th>Book author</th>
                            <th>Category title</th>
                            <th>Book img</th>

                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($books as $key=>$book)


                            <tr>
                                <a href="#">
                                    <td>{{$key+1}}</td>
                                    <td>{{$book->book_name}}</td>
                                    <td>{{$book->book_author}}</td>
                                    <td>{{$book->category_name->category_name}}</td>
                                    <td>


                                        <img src="{{asset('admin/book_images/'.explode('<!',$book->book_images)[0])}}"
                                             style="border-radius: 50%; background: red; width: 40px; height: 40px"
                                             alt=""></td>
                                    {{--                                    <img src="{{asset('files/'.explode(',',$post->photo)[0])}}" alt="image">--}}


                                    <td class="d-flex">
                                        <a href="{{route('books.show',$book)}}" class="btn btn-info"><i
                                                class="fa fa-eye"></i></a> &nbsp;

                                        <a href="{{route('books.edit',$book)}}" class="btn btn-success"><i
                                                class="fa fa-pencil"></i></a>



                                        <a href="{{ route('books.destroy', $book) }}" class="btn btn-danger" data-confirm-delete="true">Delete</a>

{{--                                        <form action="{{route('books.destroy',$book)}}" method="POST"--}}
{{--                                              onsubmit="return confirm('Rostdan ham {{$book->book_name}} o\'chirishni xoxlaysizmi  ? ')">--}}
{{--                                            @method('Delete')--}}
{{--                                            @csrf--}}
{{--                                            <button class=" btn btn-sm btn-danger show_confirm" type="submit "><i--}}
{{--                                                    class="fa fa-trash-o"></i>--}}
{{--                                            </button>--}}
{{--                                        </form>--}}

                                    </td>
                                </a>
                            </tr>


                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection