routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('main.index');
//});

Route::get('/',[\App\Http\Controllers\Main\maincontroller::class,'index'])->name('main.index');
Route::get('/search',[\App\Http\Controllers\Main\maincontroller::class,'search'])->name('search');
Route::get('/detail/{book}/',[\App\Http\Controllers\Main\maincontroller::class,'book_detail'])->name('book.detail');
Route::get('/category/{id}',[\App\Http\Controllers\Main\maincontroller::class,'category_filter'])->name('category.filter');
Route::get('/author/{id}',[\App\Http\Controllers\Main\maincontroller::class,'author_filter'])->name('author.filter');
Route::get('/card/{id}',[\App\Http\Controllers\Main\maincontroller::class,'added_cards'])->name('added.cards');
Route::get('/view_card',[\App\Http\Controllers\Main\maincontroller::class,'view_card'])->name('view.card');
Route::get('/cancel/{id}',[\App\Http\Controllers\Main\maincontroller::class,'cancel_book'])->name('cansel.book');
Route::get('/contact',[\App\Http\Controllers\Main\maincontroller::class,'contact'])->name('contact');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('admin_panel');

    Route::resource('/category', \App\Http\Controllers\Admin\categoryController::class);

    Route::resource('/books', App\Http\Controllers\Admin\BookController::class);
});
//Route::group(['prefix' => 'User', 'middleware' => ['auth', 'user']], function () {
//    Route::get('/', [\App\Http\Controllers\HomeController::class, 'user'])->name('userpanel');
//
//
//
//});

Route::post('/comment',[\App\Http\Controllers\CommentComtroller::class,'store'])->name('comment')->middleware('auth');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::post('/payment',[\App\Http\Controllers\ChecoutController::class,'session'])->name('data');
Route::get('/success',[\App\Http\Controllers\ChecoutController::class,'success'])->name('success');

resources/views/admin/partials/navbar.blade.php
<div class="page-header">
    <div class="header-wrapper row m-0">
        <form class="form-inline search-full col" action="#" method="get">
            <div class="form-group w-100">
                <div class="Typeahead Typeahead--twitterUsers">
                    <div class="u-posRelative">
                        <input class="demo-input Typeahead-input form-control-plaintext w-100" type="text" placeholder="Search Cuba .." name="q" title="" autofocus>
                        <div class="spinner-border Typeahead-spinner" role="status"><span class="sr-only">Loading...</span></div><i class="close-search" data-feather="x"></i>
                    </div>
                    <div class="Typeahead-menu"></div>
                </div>
            </div>
        </form>
        <div class="header-logo-wrapper col-auto p-0">
            <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo.png')}}" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="align-center"></i></div>
        </div>
        <div class="left-header col horizontal-wrapper ps-0">

        </div>
        <div class="nav-right col-8 pull-right right-header p-0">
            <ul class="nav-menus">
                <li class="language-nav">
                    <div class="translate_wrapper">
                        <div class="current_lang">
                            <div class="lang"><i class="flag-icon flag-icon-us"></i><span class="lang-txt">EN                               </span></div>
                        </div>
                        <div class="more_lang">
                            <div class="lang selected" data-value="en"><i class="flag-icon flag-icon-us"></i><span class="lang-txt">English<span> (US)</span></span></div>
                            <div class="lang" data-value="de"><i class="flag-icon flag-icon-uz"></i><span class="lang-txt">Uzbek</span></div>

                        </div>
                    </div>
                </li>
                <li>                         <span class="header-search"><i data-feather="search"></i></span></li>
                <li class="onhover-dropdown">
                    <div class="notification-box"><i data-feather="bell"></i>
                        <span class="badge rounded-pill badge-secondary"> </span>
                    </div>
                    <ul class="notification-dropdown onhover-show-div">
                        <li><i data-feather="bell"></i>
                            <h6 class="f-18 mb-0">Notitications</h6>
                        </li>


                        <li><a class="btn btn-primary" href="">Check all notification</a></li>
                    </ul>
                </li>
                <li class="onhover-dropdown">
                    <div class="notification-box"><i data-feather="star"></i></div>
                    <div class="onhover-show-div bookmark-flip">
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="front">
                                    <ul class="droplet-dropdown bookmark-dropdown">
                                        <li class="gradient-primary"><i data-feather="star"></i>
                                            <h6 class="f-18 mb-0">Bookmark</h6>
                                        </li>
                                        <li>
                                            <div class="row">
                                                <div class="col-4 text-center"><i data-feather="file-text"></i></div>
                                                <div class="col-4 text-center"><i data-feather="activity"></i></div>
                                                <div class="col-4 text-center"><i data-feather="users"></i></div>
                                                <div class="col-4 text-center"><i data-feather="clipboard"></i></div>
                                                <div class="col-4 text-center"><i data-feather="anchor"></i></div>
                                                <div class="col-4 text-center"><i data-feather="settings"></i></div>
                                            </div>
                                        </li>
                                        <li class="text-center">
                                            <button class="flip-btn" id="flip-btn">Add New Bookmark</button>
                                        </li>
                                    </ul>
                                </div>
                                <div class="back">
                                    <ul>
                                        <li>
                                            <div class="droplet-dropdown bookmark-dropdown flip-back-content">
                                                <input type="text" placeholder="search...">
                                            </div>
                                        </li>
                                        <li>
                                            <button class="d-block flip-back" id="flip-back">Back</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="mode"><i class="fa fa-moon-o"></i></div>
                </li>
                <li class="cart-nav onhover-dropdown">
                    <div class="cart-box"><i data-feather="shopping-cart"></i><span class="badge rounded-pill badge-primary">2</span></div>
                    <ul class="cart-dropdown onhover-show-div">
                        <li>
                            <h6 class="mb-0 f-20">Shoping Bag</h6><i data-feather="shopping-cart"></i>
                        </li>
                        <li class="mt-0">
                            <div class="media"><img class="img-fluid rounded-circle me-3 img-60" src="{{asset('admin/assets/images/ecommerce/01.jpg')}}" alt="">
                                <div class="media-body"><span>V-Neck Shawl Collar Woman's Solid T-Shirt</span>
                                    <p>Yellow(#fcb102)</p>
                                    <div class="qty-box">
                                        <div class="input-group"><span class="input-group-prepend">
                              <button class="btn quantity-left-minus" type="button" data-type="minus" data-field=""><i data-feather="minus"></i></button></span>
                                            <input class="form-control input-number" type="text" name="quantity" value="1"><span class="input-group-prepend">
                              <button class="btn quantity-right-plus" type="button" data-type="plus" data-field=""><i data-feather="plus"></i></button></span>
                                        </div>
                                    </div>
                                    <h6 class="text-end text-muted">$299.00</h6>
                                </div>
                                <div class="close-circle"><a href="#"><i data-feather="x"></i></a></div>
                            </div>
                        </li>
                        <li class="mt-0">
                            <div class="media"><img class="img-fluid rounded-circle me-3 img-60" src="{{asset('admin/assets/images/ecommerce/03.jpg')}}" alt="">
                                <div class="media-body"><span>V-Neck Shawl Collar Woman's Solid T-Shirt</span>
                                    <p>Yellow(#fcb102)</p>
                                    <div class="qty-box">
                                        <div class="input-group"><span class="input-group-prepend">
                              <button class="btn quantity-left-minus" type="button" data-type="minus" data-field=""><i data-feather="minus"></i></button></span>
                                            <input class="form-control input-number" type="text" name="quantity" value="1"><span class="input-group-prepend">
                              <button class="btn quantity-right-plus" type="button" data-type="plus" data-field=""><i data-feather="plus"></i></button></span>
                                        </div>
                                    </div>
                                    <h6 class="text-end text-muted">$299.00</h6>
                                </div>
                                <div class="close-circle"><a href="#"><i data-feather="x"></i></a></div>
                            </div>
                        </li>
                        <li>
                            <div class="total">
                                <h6 class="mb-2 mt-0 text-muted">Order Total : <span class="f-right f-20">$598.00</span></h6>
                            </div>
                        </li>
                        <li><a class="btn btn-block w-100 mb-2 btn-primary view-cart" href="cart.html">Go to shoping bag</a><a class="btn btn-block w-100 btn-secondary view-cart" href="checkout.html">Checkout</a></li>
                    </ul>
                </li>
                <li class="onhover-dropdown"><i data-feather="message-square"></i>
                    <ul class="chat-dropdown onhover-show-div">
                        <li><i data-feather="message-square"></i>
                            <h6 class="f-18 mb-0">Message Box                                    </h6>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/1.jpg')}}" alt="">
                                <div class="status-circle online"></div>
                                <div class="media-body"><span>Erica Hughes</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-success">58 mins ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/2.jpg')}}" alt="">
                                <div class="status-circle online"></div>
                                <div class="media-body"><span>Kori Thomas</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-success">1 hr ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('admin/assets/images/user/4.jpg')}}" alt="">
                                <div class="status-circle offline"></div>
                                <div class="media-body"><span>Ain Chavez</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-danger">32 mins ago</p>
                            </div>
                        </li>
                        <li class="text-center"> <a class="btn btn-primary" href="">View All     </a></li>
                    </ul>
                </li>
                <li class="maximize"><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
                <li class="profile-nav onhover-dropdown p-0 me-0">
                    <div class="media profile-media"><img class="b-r-10" src="{{asset('admin/assets/images/dashboard/profile.jpg')}}" alt="">
                        <div class="media-body"><span></span>
                            <p class="mb-0 font-roboto">Admin

                                <i class="middle fa fa-angle-down"> </i> </p>
                            {{\Illuminate\Support\Facades\Auth::user()->name}}
                        </div>

                    </div>
                    <ul class="profile-dropdown onhover-show-div">

                        <li><a href=""><i data-feather="settings"></i><span>Settings</span></a></li>
                        <li><a class="" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i data-feather="log-out"> </i><span>Log out</span></a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form></li>

                    </ul>
                </li>
            </ul>
        </div>
        <script class="result-template" type="text/x-handlebars-template">
            <div class="ProfileCard u-cf">
                <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
                <div class="ProfileCard-details">
                    <div class="ProfileCard-realName"></div>
                </div>
            </div>
        </script>
        <script class="empty-template" type="text/x-handlebars-template"><div class="EmptyMessage">Your search turned up 0 results. This most likely means the backend is down, yikes!</div></script>
    </div>
</div>

resources/views/admin/partials/seidbar.blade.php
<div class="sidebar-wrapper">
    <div>
        <div class="logo-wrapper"><a href="index.html"><img class="img-fluid for-light" src="{{asset('admin/assets/images/logo/logo.png')}}" alt=""><img class="img-fluid for-dark" src="../assets/images/logo/logo_dark.png" alt=""></a>
            <div class="back-btn"><i class="fa fa-angle-left"></i></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
        </div>
        <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo-icon.png')}}" alt=""></a></div>
        <nav class="sidebar-main">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="sidebar-menu">
                <ul class="sidebar-links" id="simple-bar">
                    <li class="back-btn"><a href="index.html"><img class="img-fluid" src="{{asset('admin/assets/images/logo/logo-icon.png')}}" alt=""></a>
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">
                        <div>
                            <a href="{{route('main.index')}}"> Main blade</a>
                        </div>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="book"></i><span >Category </span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/category/create') || request()->is('dashboard/category')) || request()->is('dashboard/category/*/edit')  ? 'd-block': ''}}">
                            <li><a href="{{route('category.create')}}" style="color: {{request()->is('dashboard/category/create')? '#6600FF': ''}}">Add new category</a></li>
                            <li><a href="{{route('category.index')}}" style="color: {{request()->is('dashboard/category')? '#6600FF': ''}}">View category</a></li>
                        </ul>

                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="book"></i><span >Book</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/books/create') || request()->is('dashboard/books')) || request()->is('dashboard/books/*/edit')  ? 'd-block': ''}}">
                            <li><a href="{{route('books.create')}}" style="color: {{request()->is('dashboard/books/create')? '#6600FF': ''}}">Add new book</a></li>
                            <li><a href="{{route('books.index')}}" style="color: {{request()->is('dashboard/books')? '#6600FF': ''}}">View books</a></li>
                        </ul>

                    </li>



                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </nav>
    </div>
</div>